platform/mikro-e: enable slip protocol
CreatorDev/contiki pull request #51
Opened 2017-02-13 10:03 UTC by manohar-narkhede-imgtec

Signed-off-by: Manohar Narkhede <Manohar.Narkhede@imgtec.com>

2017-02-13 10:06 UTC, Avinash95 commented on platform/mikro-e/Makefile.mikro-e
> +CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES) slip.c
you can append the slip.c filename to CONTIKI_TARGET_SOURCEFILES variable as it is defined in the same makefile

2017-02-13 10:32 UTC, manohar-narkhede-imgtec commented on platform/mikro-e/Makefile.mikro-e
> +CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES) slip.c
It is not TARGET(Mikro-e) related.

2017-02-13 10:59 UTC, mtusnio requested changes
Does RPL work without SLIP? What's the reason we need SLIP configured by default? I'm a bit worried here since this would use one UART line for debug, one for SLIP, leaving no room for clickers using UART.

2017-02-13 11:26 UTC, Avinash95 commented on platform/mikro-e/Makefile.mikro-e
> +CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES) slip.c
But it's inside target(Mikro-e) makefile, so isn't it related to Mikro-e?

2017-02-14 06:50 UTC, manohar-narkhede-imgtec commented on platform/mikro-e/Makefile.mikro-e
> +CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES) slip.c
slip.c is Contiki common source code so it should be part of CONTIKI_SOURCEFILES which is independent of the platform. The platform specific source code will be part of CONTIKI_TARGET_SOURCEFILES.

2017-02-14 06:56 UTC, manohar-narkhede-imgtec commented
RPL works without SLIP. RPL as such does not have any dependency on SLIP. 

As the rpl border router was running on Clicker, the SLIP required for its functionality. The border router can run on Ci 40.

2017-02-14 10:33 UTC, mtusnio commented
I don't like adding SLIP by default, how do you configure defines for a border router? It'd make sense to add SLIP then rather than have it all the time. What's exactly SLIP used for in RPL, what does it communicate with, or is it just for debug?

2017-02-17 08:49 UTC, Shpinkso commented
What's happening with this please, don't just let it sit here forever.

2017-02-17 09:04 UTC, manohar-narkhede-imgtec commented
SLIP has nothing to do with. It is implementation of Serial Line Internet Protocol which provides outside n/w connectibity.

The border router can be used without RPL. It is part of core Contiki source code. Already there is source code getting compiled even if that is not getting used by application. Should we remove that code also from Makefile? The examples are common for other platforms also.

2017-02-22 14:52 UTC, mtusnio commented
We do not enable any other UART apart from the one we use for debug by default, @francois-berder-imgtec you mentioned you will do a PR for that, is this one blocked until that's done?

2017-02-23 10:34 UTC, mtusnio commented
I believe we need https://github.com/CreatorDev/contiki/pull/69 merged first.

2017-02-23 11:10 UTC, mtusnio commented
@manohar-narkhede-imgtec Can you rebase this branch and modify the PR to match changes done by @francois-berder-imgtec ?

2017-02-24 10:46 UTC, mtusnio requested changes

2017-02-24 10:46 UTC, mtusnio commented on platform/mikro-e/Makefile.mikro-e
> +  CONTIKI_PLAT_DEFS += -D __USE_UART_PORT3__
Francois's change already added this by default, we can get rid of the extra -D __USE_UART_PORT3__

2017-02-24 10:46 UTC, mtusnio commented on platform/mikro-e/Makefile.mikro-e
> +  CONTIKI_PLAT_DEFS += -D __USE_UART_PORT2__
Can remove this one as well

2017-02-27 11:16 UTC, closed without merging