Add rule to convert *.mikro-e files to *.hex
CreatorDev/contiki pull request #56
Opened 2017-02-16 10:52 UTC by Avinash95

Also added TARGET=mikro-e if TARGET is not defined

Signed-off-by: Avinash Tahakik <Avinash.Tahakik@imgtec.com>

2017-02-16 11:02 UTC, mtusnio commented
Is there any reason why we shouldn't just add this step in mikro-e Makefile for all projects?

2017-02-16 11:59 UTC, manohar-narkhede-imgtec commented on cpu/pic32/Makefile.pic32
> +%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
This Makefile is specific to PIC32. Should we have $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) here??

2017-02-16 12:09 UTC, Avinash95 commented on cpu/pic32/Makefile.pic32
> +%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
even though its specific to PIC32, it will come into picture when we are building a project, besides this is how it's done on creator branch

2017-02-16 12:23 UTC, manohar-narkhede-imgtec approved these changes

2017-02-16 13:28 UTC, mtusnio commented
Have you checked if this would work in some way in Makefile.mikro-e? I doubt upstream will accept a Makefile with xc32 instructions, and we are pushing to 3.0-mikro-e. I'd rather have that in the platform file.

2017-02-16 13:29 UTC, mtusnio requested changes
Have you checked if this would work in some way in Makefile.mikro-e? I doubt upstream will accept a Makefile with xc32 instructions, and we are pushing to 3.0-mikro-e. I'd rather have that in the platform file.

2017-02-16 13:45 UTC, mtusnio requested changes

2017-02-16 13:45 UTC, mtusnio commented on cpu/pic32/Makefile.pic32
> +%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
It'd be good to get some clarification regarding what it does & if we need all of those bits to do the rule.

2017-02-21 11:35 UTC, mtusnio commented
As we discussed it all looks good, can you only split this into two commits? One for the rule, one to accommodate the Makefile changes. Also, the commits will need a "platform/mikro-e:" prefix to them.

2017-02-21 11:35 UTC, mtusnio requested changes
As we discussed it all looks good, can you only split this into two commits? One for the rule, one to accommodate the Makefile changes. Also, the commits will need a "platform/mikro-e:" prefix to them.

2017-02-21 16:31 UTC, Avinash95 commented
Closing this PR.
Done in  #64

2017-02-21 16:31 UTC, closed without merging