Add rule to convert *.mikro-e files to *.hex
CreatorDev/contiki pull request #64
Opened 2017-02-21 16:31 UTC by Avinash95

this connects #55

2017-02-22 06:49 UTC, abhijit-mahajani-imgtec requested changes

2017-02-22 06:49 UTC, abhijit-mahajani-imgtec commented on platform/mikro-e/apps/test-button/Makefile
> +all: test-button
why did you remove the $(CONTIKI_PROJECT) from all?

2017-02-22 06:49 UTC, abhijit-mahajani-imgtec commented on platform/mikro-e/apps/test-button/Makefile
> +ifndef TARGET
Either if all these sample/test apps are not dependent on platform then it should not be under mikro-e, but if its dependent, then why can't we have TARGET=mikro-e unconditionally?

2017-02-22 07:21 UTC, Avinash95 commented on platform/mikro-e/apps/test-button/Makefile
> +all: test-button
because it's not needed

2017-02-23 11:49 UTC, mtusnio commented
I've just tried making the sample-app, removed main.hex, then re-ran "make". Until you run make clean the makefile doesn't treat main.hex as a file it needs to regenerate.

2017-03-01 15:38 UTC, mtusnio requested changes
Breaks CI since it introduces a dependency on CONTIKI_PROJECT.

2017-03-01 15:38 UTC, mtusnio commented on platform/mikro-e/Makefile.mikro-e
> +all: $(CONTIKI_PROJECT).$(TARGET) bin2hex
When using all you can do it much easier, you can get rid of the CUSTOM_RULE_LINK and the custom rule below and just do it like this (see full patch below):

all: $(CONTIKI_PROJECT).$(TARGET)
    xc32-bin2hex $(CONTIKI_PROJECT).mikro-e

This is the kind of a fix I was thinking of, it's just in this case we have to get rid of the dependency on CONTIKI_PROJECT. 

```diff --git a/platform/mikro-e/Makefile.mikro-e b/platform/mikro-e/Makefile.mikro-e
index d2bea39..6fdb602 100755
--- a/platform/mikro-e/Makefile.mikro-e
+++ b/platform/mikro-e/Makefile.mikro-e
@@ -55,20 +55,15 @@ CFLAGS += -DIEEE802154_CONF_PANID=$(PAN_ID)
 
 include $(CONTIKI)/cpu/pic32/Makefile.pic32
 
-CUSTOM_RULE_LINK=1
+#CUSTOM_RULE_LINK=1
 
 ### CPU-dependent cleanup files
 CLEAN += *.hex *.$(TARGET)
 
-.PHONY: bin2hex
-
-all: $(CONTIKI_PROJECT).$(TARGET) bin2hex
-
-$(CONTIKI_PROJECT).$(TARGET): $(CONTIKI_PROJECT).co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
-       $(TRACE_LD)
-       $(Q)$(LD) $(LDFLAGS) $(TARGET_STARTFILES) ${filter-out %.a,$^} ${filter %.a,$^} $(TARGET_LIBFILES) -o $@
-
-bin2hex:
-       xc32-bin2hex $(CONTIKI_PROJECT).$(TARGET)
-
+#%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a
+#      $(TRACE_LD)
+#      $(Q)$(LD) $(LDFLAGS) $(TARGET_STARTFILES) ${filter-out %.a,$^} \
+#              ${filter %.a,$^} $(TARGET_LIBFILES) -o $@
 
+all: $(CONTIKI_PROJECT).$(TARGET)
+       xc32-bin2hex $(CONTIKI_PROJECT).mikro-e
```

2017-03-01 15:38 UTC, mtusnio commented on platform/mikro-e/Makefile.mikro-e
> +bin2hex:
Fails when make -j9 is used, breaks multithreaded builds.

2017-03-07 17:02 UTC, mtusnio submitted a review, later dismissed
The second commit seems to add more than the commit message implies, can you split it into separate commit(s)?

2017-03-10 10:07 UTC, abhijit-mahajani-imgtec approved these changes

2017-03-10 10:07 UTC, abhijit-mahajani-imgtec requested changes
Need to update the branch

2017-03-17 07:41 UTC, abhijit-mahajani-imgtec approved these changes

2017-03-20 10:54 UTC, mtusnio reviewed
According to this - https://www.gnu.org/software/make/manual/html_node/Force-Targets.html - you can do something along those lines to always force regeneration of the hex file:

```diff
diff --git a/platform/mikro-e/Makefile.mikro-e b/platform/mikro-e/Makefile.mikro-e
index 1b4fa63..8f45087 100755
--- a/platform/mikro-e/Makefile.mikro-e
+++ b/platform/mikro-e/Makefile.mikro-e
@@ -70,8 +70,10 @@ CUSTOM_RULE_LINK = 1
        $(Q)$(LD) $(LDFLAGS) $(TARGET_STARTFILES) ${filter-out %.a,$^} \
            ${filter %.a,$^} $(TARGET_LIBFILES) -o $@
 
-%.hex: %.bin
+%.hex: %.bin FORCE
        xc32-bin2hex $<
 
+FORCE:
+
 %.$(TARGET): %.bin %.hex
        mv $< $@
```
The downside is that the final .c file will be always compiled when you run "make", since it will force a build of the hex file, but that solves the issue of the hex file not rebuilding if removed.

2017-03-21 10:57 UTC, mtusnio approved these changes

2017-03-22 10:20 UTC, merged