apps: add letmecreateiot submodule
CreatorDev/contiki pull request #80
Opened 2017-03-06 14:31 UTC by mtusnio

Adds LetMeCreateIoT as an app.

2017-03-06 14:41 UTC, GonZo commented
I'm curious to understand if this is the best way of doing with submodules.

2017-03-07 10:52 UTC, manohar-narkhede-imgtec requested changes

2017-03-07 10:52 UTC, manohar-narkhede-imgtec commented on .gitmodules
> +[submodule "apps/letmecreateiot"]
As it is specific to Mikro-e platform, it can be downloaded at platform/mikro-e/apps/letmecreateiot.

2017-03-07 11:04 UTC, mtusnio commented on .gitmodules
> +[submodule "apps/letmecreateiot"]
Makes sense, I'll move it & update the app to make sure everything builds.

2017-03-08 06:14 UTC, manohar-narkhede-imgtec approved these changes

2017-03-08 06:17 UTC, manohar-narkhede-imgtec commented
Do we need to add compilation of some of the examples in letmecreateIot in Jenkinsfile also?

2017-03-08 10:20 UTC, mtusnio commented
It'd make sense to kick LetMeCreateIoT builds whenever we are merging into Creator, however that would require switching LMCIoT CI into a Jenkinsfile and all that. I'm not sure if it's part of this task, I think it's a wider "redo LMCIoT CI" thing.

2017-03-08 15:38 UTC, merged